services:
  video_in:
    image: containers.openfilter.io/plainsightai/openfilter-video-in:v0.1.10
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: VideoIn
      FILTER_SOURCES: file:///video.mp4!sync
      FILTER_OUTPUTS: tcp://*
    volumes:
      - ./data/patty_steak.mp4:/video.mp4:ro

  frame_dedup_filter:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: filter-frame-dedup:local
    pull_policy: never
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-DEBUG}
      FILTER_ID: FrameDedupFilter
      FILTER_SOURCES: tcp://video_in
      FILTER_OUTPUTS: tcp://*
      FILTER_OUTPUT_FOLDER: /output
      FILTER_SAVE_IMAGES: "true"
      FILTER_MIN_TIME_BETWEEN_FRAMES: 0.0
      FILTER_USE_MODEL_DEDUP: "true"
      FILTER_MODEL_DEDUP_THRESHOLD: 0.92
      FILTER_MODEL_HF_ID: "facebook/dinov3-vits16-pretrain-lvd1689m"
      HF_TOKEN: ${HF_TOKEN}
      HF_HUB_OFFLINE: 0
    volumes:
      - ./output/model_mintime0_dinov3_patty_steak:/output
      # - ./filter_frame_dedup/filter.py:/app/filter_frame_dedup/filter.py:rw
  webvis:
    image: containers.openfilter.io/plainsightai/openfilter-webvis:v0.1.10
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-}
      FILTER_ID: Webvis
      FILTER_SOURCES: tcp://frame_dedup_filter
    ports:
      - 8001:8000